### ISSUE TITLE
bot是群主权限不足

### ISSUE THREAD

**Issue by Jerry080801** [Ikaros-521/nonebot_plugin_random_ban#1]

**Comment by Ikaros-521** [comment]
好家伙 这我还真没测过，待我试试

**Comment by Ikaros-521** [comment]
> _No description provided._

刚测了下，bot是群主，我的bot的管理员+群管，可以禁言。
![image](https://user-images.githubusercontent.com/40910637/209931763-bb2d6b9c-0999-4fdb-b370-0894b00feb78.png)

**Comment by Ikaros-521** [comment]
![image](https://user-images.githubusercontent.com/40910637/209932136-39e8b378-e587-41dd-999a-5c7c5d2af5d1.png)

权限设置应该是没有问题的，可能是传入的禁言时间有问题，导致禁言的下发出错了。 
可以再试试看

**Comment by Jerry080801** [comment]
好的
