### ISSUE TITLE
希望能自动识别禁言时间为小时或者分钟

### ISSUE THREAD

**Issue by natsuwakisekinai** [Ikaros-521/nonebot_plugin_random_ban#2]
能识别禁言时间为小时或者分钟之类的吗，不然还要人工计算一下
比如/口球 10分钟
/随禁 10小时
默认识别可为小时或者分钟 /口球 10

**Comment by Ikaros-521** [comment]
可以，加入下一版本开发计划

**Comment by Ikaros-521** [comment]
v0.2.0已发布
### 0.2.0

- 新增 传参的单位兼容，分、分钟、时、小时、天。
- 修改 艾特 为 回复的形式。
- 优化代码。
