### ISSUE TITLE
（bug）时间单位识别错误？

### ISSUE THREAD

**Issue by natsuwakisekinai** [Ikaros-521/nonebot_plugin_random_ban#3]
结果：现在的 天/小时 都会等于分钟

**Comment by Ikaros-521** [comment]
ok  我有空的时候 看看

**Comment by natsuwakisekinai** [comment]
示例：口球 1天
结果：禁言 1分钟
小时 也是一样的效果
不会是我的问题吧（）

**Comment by Ikaros-521** [comment]
可能刚好随机值相同，可以多试几组 还是一样的话 那肯定是解析有问题

**Comment by natsuwakisekinai** [comment]
还有个小问题
如果指令中的时间过长（超过43199分钟），也会回复禁言失败，如果能加个上限就更好了(43199分钟=29天23小时59分钟）

**Comment by Ikaros-521** [comment]
> 还有个小问题 如果指令中的时间过长（超过43199分钟），也会回复禁言失败，如果能加个上限就更好了(43199分钟=29天23小时59分钟）

这个倒不是什么问题，超过默认按最大值就行

**Comment by Ikaros-521** [comment]
v0.2.1修复2个问题，这次应该，大概，也许，或许，没有问题了
